# """
# Validation Excel builder.

# Takes the S/4 LTMC workbook exactly as it was generated by /process (rows
# with warnings stay red, "Warnings" sheet stays) and places the ECC source
# value NEXT TO every S/4 column that is produced by a mapping:

#     S/4 BUKRS | ECC Company Code | ... | S/4 KUNNR | ECC Customer Number | ...

# so a reviewer can compare the mapped value with where it came from without
# switching files. The result is a separate validation file; the staged S/4
# workbook on disk is never modified.
# """
# import io
# from copy import copy

# import openpyxl
# from openpyxl.cell.cell import MergedCell
# from openpyxl.styles import Alignment, Font, PatternFill
# from openpyxl.utils import column_index_from_string, get_column_letter

# from backend.services.ar_processor import (
#     HEADER_ROW,
#     TECHNICAL_NAME_ROW,
#     TEMPLATE_SHEET,
#     WARNING_ROW_FILL,
#     XREF1_SOURCE_FIELD,
#     _detect_data_start_row,
#     clean_string,
# )

# # (S/4 technical field, ECC source field, header shown for the ECC column)
# MAPPED_FIELDS = [
#     ("BUKRS", "BUKRS", "ECC Company Code"),
#     ("KUNNR", "KUNNR", "ECC Customer Number"),
#     ("BLART", "BLART", "ECC Document Type"),
#     ("ZTERM", "ZTERM", "ECC Payment Terms"),
# ]

# ECC_COLUMN_WIDTH = 22
# ECC_HEADER_FILL = PatternFill(start_color="FF9DC3E6", end_color="FF9DC3E6", fill_type="solid")
# ECC_DATA_FILL = PatternFill(start_color="FFEAF1FB", end_color="FFEAF1FB", fill_type="solid")


# def _is_warning_row(cell) -> bool:
#     fill = cell.fill
#     return (
#         fill is not None
#         and fill.fill_type == "solid"
#         and fill.start_color is not None
#         and fill.start_color.rgb == WARNING_ROW_FILL.start_color.rgb
#     )


# def build_validation_workbook(s4_path, ecc_records: list[dict]) -> io.BytesIO:
#     """
#     `s4_path`     staged S/4 workbook produced by /process.
#     `ecc_records` rows of the staged ECC workbook (file_store.read_ecc_workbook),
#                   in the same order the processor read them.
#     Raises ValueError if the two files are out of sync (re-run Process).
#     """
#     wb = openpyxl.load_workbook(s4_path)
#     ws = wb[TEMPLATE_SHEET] if TEMPLATE_SHEET in wb.sheetnames else wb[wb.sheetnames[0]]

#     technical = {}
#     for col in range(1, ws.max_column + 1):
#         name = clean_string(ws.cell(row=TECHNICAL_NAME_ROW, column=col).value)
#         if name:
#             technical[name] = col

#     missing = [f for f, _, _ in MAPPED_FIELDS if f not in technical]
#     if missing:
#         raise ValueError(f"S/4 workbook has no column(s) for: {', '.join(missing)}.")

#     data_start = _detect_data_start_row(ws, technical)
#     ecc_ci = [{str(k).upper(): v for k, v in rec.items()} for rec in ecc_records]

#     # --- make sure ECC row i really is the source of S/4 row i -----------
#     xref_col = technical.get("XREF1")
#     s4_rows = 0
#     for r in range(data_start, ws.max_row + 1):
#         if any(ws.cell(row=r, column=c).value not in (None, "") for c in (1, 2, technical["KUNNR"])):
#             s4_rows += 1
#     if s4_rows != len(ecc_ci):
#         raise ValueError(
#             f"S/4 workbook has {s4_rows} rows but the ECC file has {len(ecc_ci)}. "
#             "Run Process again so both files are from the same run."
#         )
#     if xref_col:
#         for i, rec in enumerate(ecc_ci):
#             s4_ref = clean_string(ws.cell(row=data_start + i, column=xref_col).value)
#             ecc_ref = clean_string(rec.get(XREF1_SOURCE_FIELD))
#             if s4_ref != ecc_ref:
#                 raise ValueError(
#                     f"ECC row {i + 1} (document {ecc_ref}) does not match S/4 row "
#                     f"{data_start + i} (reference {s4_ref}). Run Process again."
#                 )

#     # --- column layout: one new column right after each mapped S/4 column ---
#     insert_after = sorted(technical[f] for f, _, _ in MAPPED_FIELDS)

#     def shift(col: int) -> int:
#         return col + sum(1 for p in insert_after if p < col)

#     max_col = ws.max_column
#     max_row = ws.max_row

#     # remember what the shift would break: merged headers and column widths
#     merged = [
#         (r.min_row, r.max_row, r.min_col, r.max_col) for r in list(ws.merged_cells.ranges)
#     ]
#     for rng in list(ws.merged_cells.ranges):
#         ws.unmerge_cells(str(rng))

#     widths = {}
#     for key, dim in ws.column_dimensions.items():
#         lo = dim.min or column_index_from_string(key)
#         hi = min(dim.max or lo, max_col)
#         for c in range(lo, hi + 1):
#             widths[c] = dim.width
#     for key in list(ws.column_dimensions.keys()):
#         del ws.column_dimensions[key]

#     # move columns right-to-left so nothing is overwritten
#     for col in range(max_col, 0, -1):
#         k = shift(col) - col
#         if k:
#             letter = get_column_letter(col)
#             ws.move_range(f"{letter}1:{letter}{max_row}", cols=k)

#     for min_row, max_r, min_col, max_c in merged:
#         ws.merge_cells(
#             start_row=min_row, end_row=max_r,
#             start_column=shift(min_col), end_column=shift(max_c),
#         )

#     for col in range(1, max_col + 1):
#         letter = get_column_letter(shift(col))
#         ws.column_dimensions[letter].width = widths.get(col, 20)

#     ws.freeze_panes = f"A{HEADER_ROW}"   # keep the header rows visible

#     # --- fill the ECC columns --------------------------------------------
#     for s4_field, ecc_field, label in MAPPED_FIELDS:
#         s4_col = shift(technical[s4_field])
#         ecc_col = s4_col + 1
#         ws.column_dimensions[get_column_letter(ecc_col)].width = ECC_COLUMN_WIDTH

#         for r in range(TECHNICAL_NAME_ROW - 1, data_start):      # header block
#             src = ws.cell(row=r, column=s4_col)
#             dst = ws.cell(row=r, column=ecc_col)
#             if isinstance(dst, MergedCell):
#                 continue
#             dst._style = copy(src._style)
#         for r, text in (
#             (TECHNICAL_NAME_ROW, f"ECC_{ecc_field}"),
#             (HEADER_ROW - 1, f"Source value of {ecc_field} in the ECC file, "
#                              f"shown next to the S/4 {s4_field} it was mapped to."),
#             (HEADER_ROW, label),
#         ):
#             dst = ws.cell(row=r, column=ecc_col)
#             if isinstance(dst, MergedCell):
#                 continue
#             dst.value = text
#             if r != HEADER_ROW - 1:
#                 dst.fill = ECC_HEADER_FILL
#                 dst.font = Font(bold=True)
#         ws.cell(row=HEADER_ROW - 1, column=ecc_col).alignment = Alignment(wrap_text=True, vertical="top")

#         for i, rec in enumerate(ecc_ci):
#             r = data_start + i
#             src = ws.cell(row=r, column=s4_col)
#             dst = ws.cell(row=r, column=ecc_col)
#             dst._style = copy(src._style)
#             dst.number_format = "@"
#             raw = rec.get(ecc_field.upper())
#             text = "" if raw is None else str(raw).strip()
#             dst.value = text or None
#             if not _is_warning_row(src):
#                 dst.fill = ECC_DATA_FILL   # red rows keep their red

#     wb.active = wb.sheetnames.index(ws.title)
#     out = io.BytesIO()
#     wb.save(out)
#     out.seek(0)
#     return out


"""
Validation Excel builder.

Takes the S/4 LTMC workbook exactly as it was generated by /process (rows
with warnings stay red, "Warnings" sheet stays) and places the ECC source
value NEXT TO every S/4 column that is produced by a mapping:

    S/4 BUKRS | ECC Company Code | ... | S/4 KUNNR | ECC Customer Number | ...

so a reviewer can compare the mapped value with where it came from without
switching files. The result is a separate validation file; the staged S/4
workbook on disk is never modified.
"""
import io
from copy import copy

import openpyxl
from openpyxl.cell.cell import MergedCell
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import column_index_from_string, get_column_letter
from openpyxl.worksheet.views import Selection

from backend.services.ar_processor import (
    HEADER_ROW,
    TECHNICAL_NAME_ROW,
    TEMPLATE_SHEET,
    WARNING_ROW_FILL,
    XREF1_SOURCE_FIELD,
    _detect_data_start_row,
    clean_string,
)

# (S/4 technical field, ECC source field, header shown for the ECC column)
MAPPED_FIELDS = [
    ("BUKRS", "BUKRS", "ECC Company Code"),
    ("KUNNR", "KUNNR", "ECC Customer Number"),
    ("BLART", "BLART", "ECC Document Type"),
    ("ZTERM", "ZTERM", "ECC Payment Terms"),
]

ECC_COLUMN_WIDTH = 22
ECC_HEADER_FILL = PatternFill(start_color="FF9DC3E6", end_color="FF9DC3E6", fill_type="solid")
ECC_DATA_FILL = PatternFill(start_color="FFEAF1FB", end_color="FFEAF1FB", fill_type="solid")


def _is_warning_row(cell) -> bool:
    fill = cell.fill
    return (
        fill is not None
        and fill.fill_type == "solid"
        and fill.start_color is not None
        and fill.start_color.rgb == WARNING_ROW_FILL.start_color.rgb
    )


def build_validation_workbook(s4_path, ecc_records: list[dict]) -> io.BytesIO:
    """
    `s4_path`     staged S/4 workbook produced by /process.
    `ecc_records` rows of the staged ECC workbook (file_store.read_ecc_workbook),
                  in the same order the processor read them.
    Raises ValueError if the two files are out of sync (re-run Process).
    """
    wb = openpyxl.load_workbook(s4_path)
    ws = wb[TEMPLATE_SHEET] if TEMPLATE_SHEET in wb.sheetnames else wb[wb.sheetnames[0]]

    technical = {}
    for col in range(1, ws.max_column + 1):
        name = clean_string(ws.cell(row=TECHNICAL_NAME_ROW, column=col).value)
        if name:
            technical[name] = col

    missing = [f for f, _, _ in MAPPED_FIELDS if f not in technical]
    if missing:
        raise ValueError(f"S/4 workbook has no column(s) for: {', '.join(missing)}.")

    data_start = _detect_data_start_row(ws, technical)
    ecc_ci = [{str(k).upper(): v for k, v in rec.items()} for rec in ecc_records]

    # --- make sure ECC row i really is the source of S/4 row i -----------
    xref_col = technical.get("XREF1")
    s4_rows = 0
    for r in range(data_start, ws.max_row + 1):
        if any(ws.cell(row=r, column=c).value not in (None, "") for c in (1, 2, technical["KUNNR"])):
            s4_rows += 1
    if s4_rows != len(ecc_ci):
        raise ValueError(
            f"S/4 workbook has {s4_rows} rows but the ECC file has {len(ecc_ci)}. "
            "Run Process again so both files are from the same run."
        )
    if xref_col:
        for i, rec in enumerate(ecc_ci):
            s4_ref = clean_string(ws.cell(row=data_start + i, column=xref_col).value)
            ecc_ref = clean_string(rec.get(XREF1_SOURCE_FIELD))
            if s4_ref != ecc_ref:
                raise ValueError(
                    f"ECC row {i + 1} (document {ecc_ref}) does not match S/4 row "
                    f"{data_start + i} (reference {s4_ref}). Run Process again."
                )

    # --- column layout: one new column right after each mapped S/4 column ---
    insert_after = sorted(technical[f] for f, _, _ in MAPPED_FIELDS)

    def shift(col: int) -> int:
        return col + sum(1 for p in insert_after if p < col)

    max_col = ws.max_column
    max_row = ws.max_row

    # remember what the shift would break: merged headers and column widths
    merged = [
        (r.min_row, r.max_row, r.min_col, r.max_col) for r in list(ws.merged_cells.ranges)
    ]
    for rng in list(ws.merged_cells.ranges):
        ws.unmerge_cells(str(rng))

    widths = {}
    for key, dim in ws.column_dimensions.items():
        lo = dim.min or column_index_from_string(key)
        hi = min(dim.max or lo, max_col)
        for c in range(lo, hi + 1):
            widths[c] = dim.width
    for key in list(ws.column_dimensions.keys()):
        del ws.column_dimensions[key]

    # move columns right-to-left so nothing is overwritten
    for col in range(max_col, 0, -1):
        k = shift(col) - col
        if k:
            letter = get_column_letter(col)
            ws.move_range(f"{letter}1:{letter}{max_row}", cols=k)

    for min_row, max_r, min_col, max_c in merged:
        ws.merge_cells(
            start_row=min_row, end_row=max_r,
            start_column=shift(min_col), end_column=shift(max_c),
        )

    for col in range(1, max_col + 1):
        letter = get_column_letter(shift(col))
        ws.column_dimensions[letter].width = widths.get(col, 20)

    # The template's view has xSplit+ySplit with selections for 3 panes.
    # Changing the freeze point without resetting them leaves duplicate /
    # non-existent pane selections, which makes Excel show the "found a
    # problem with some content" repair prompt. Reset to one valid selection.
    ws.sheet_view.pane = None
    ws.sheet_view.selection = [Selection(activeCell="A1", sqref="A1")]
    ws.freeze_panes = f"A{HEADER_ROW}"   # keep the header rows visible

    # --- fill the ECC columns --------------------------------------------
    for s4_field, ecc_field, label in MAPPED_FIELDS:
        s4_col = shift(technical[s4_field])
        ecc_col = s4_col + 1
        ws.column_dimensions[get_column_letter(ecc_col)].width = ECC_COLUMN_WIDTH

        for r in range(TECHNICAL_NAME_ROW - 1, data_start):      # header block
            src = ws.cell(row=r, column=s4_col)
            dst = ws.cell(row=r, column=ecc_col)
            if isinstance(dst, MergedCell):
                continue
            dst._style = copy(src._style)
        for r, text in (
            (TECHNICAL_NAME_ROW, f"ECC_{ecc_field}"),
            (HEADER_ROW - 1, f"Source value of {ecc_field} in the ECC file, "
                             f"shown next to the S/4 {s4_field} it was mapped to."),
            (HEADER_ROW, label),
        ):
            dst = ws.cell(row=r, column=ecc_col)
            if isinstance(dst, MergedCell):
                continue
            dst.value = text
            if r != HEADER_ROW - 1:
                dst.fill = ECC_HEADER_FILL
                dst.font = Font(bold=True)
        ws.cell(row=HEADER_ROW - 1, column=ecc_col).alignment = Alignment(wrap_text=True, vertical="top")

        for i, rec in enumerate(ecc_ci):
            r = data_start + i
            src = ws.cell(row=r, column=s4_col)
            dst = ws.cell(row=r, column=ecc_col)
            dst._style = copy(src._style)
            dst.number_format = "@"
            raw = rec.get(ecc_field.upper())
            text = "" if raw is None else str(raw).strip()
            dst.value = text or None
            if not _is_warning_row(src):
                dst.fill = ECC_DATA_FILL   # red rows keep their red

    wb.active = wb.sheetnames.index(ws.title)
    out = io.BytesIO()
    wb.save(out)
    out.seek(0)
    return out